version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: anti-spoofing-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      ui:
        condition: service_healthy
      ml-model:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - anti-spoofing-network

  ml-model:
    image: psp24/anti_spoofing_ml-model:latest
    container_name: anti-spoofing-ml-model
    environment:
      - MODELS_FOLDER=${MODELS_FOLDER}
      - MODEL_FILE_NAME=${MODEL_FILE_NAME}
      - IMAGE_SIZE=${IMAGE_SIZE}
      - EXECUTION_PROVIDER=${EXECUTION_PROVIDER}
    volumes:
      - ml-models:/app/models
    networks:
      - anti-spoofing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ml-model:${ML_MODEL_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  database:
    image: psp24/anti_spoofing_database:latest
    container_name: anti-spoofing-database
    volumes:
      - db-data:/api/database
    depends_on:
      ml-model:
        condition: service_healthy
      ui:
        condition: service_healthy
    networks:
      - anti-spoofing-network
    environment:
      - ML_SERVICE_URL=http://ml-model:${ML_MODEL_PORT}
      - CHROMA_DB_PATH=${CHROMA_DB_PATH}
      - ML_MODEL_PORT=${ML_MODEL_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://database:${DATABASE_SERVICE_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  ui:
    image: psp24/anti_spoofing_ui:latest
    container_name: anti-spoofing-ui
    networks:
      - anti-spoofing-network
    environment:
      - REACT_APP_API_URL=http://database:${DATABASE_SERVICE_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ui:${API_SERVICE_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ml-models:
    driver: local
  db-data:
    driver: local

networks:
  anti-spoofing-network:
    driver: bridge